"""CLI controller for growth progress calculation (adapter layer)."""

import argparse

from datetime import datetime
from typing import Optional

from agrr_core.usecase.gateways.crop_profile_gateway import CropProfileGateway
from agrr_core.usecase.gateways.weather_gateway import WeatherGateway
from agrr_core.usecase.ports.input.growth_progress_calculate_input_port import (
    GrowthProgressCalculateInputPort,
)
from agrr_core.usecase.ports.output.growth_progress_calculate_output_port import (
    GrowthProgressCalculateOutputPort,
)
from agrr_core.usecase.interactors.growth_progress_calculate_interactor import (
    GrowthProgressCalculateInteractor,
)
from agrr_core.usecase.dto.growth_progress_calculate_request_dto import (
    GrowthProgressCalculateRequestDTO,
)
from agrr_core.usecase.dto.growth_progress_calculate_response_dto import (
    GrowthProgressCalculateResponseDTO,
)
from agrr_core.framework.logging.agrr_logger import get_logger

class GrowthProgressCliController(GrowthProgressCalculateInputPort):
    """CLI controller implementing Input Port for growth progress calculation."""

    def __init__(
        self,
        crop_profile_gateway: CropProfileGateway,
        weather_gateway: WeatherGateway,
        presenter: GrowthProgressCalculateOutputPort,
    ) -> None:
        """Initialize with injected dependencies.
        
        Args:
            crop_profile_gateway: Gateway for crop profile operations
            weather_gateway: Gateway for weather data operations
            presenter: Presenter for output formatting
        """
        self.crop_profile_gateway = crop_profile_gateway
        self.weather_gateway = weather_gateway
        self.presenter = presenter
        self.logger = get_logger()
        
        # Instantiate interactor inside controller
        self.interactor = GrowthProgressCalculateInteractor(
            crop_profile_gateway=self.crop_profile_gateway,
            weather_gateway=self.weather_gateway,
        )

    def execute(
        self, request: GrowthProgressCalculateRequestDTO
    ) -> GrowthProgressCalculateResponseDTO:
        """Execute the growth progress calculation use case.
        
        Implementation of Input Port interface.
        
        Args:
            request: Request DTO containing calculation parameters
            
        Returns:
            Response DTO containing growth progress data
        """
        return self.interactor.execute(request)

    def create_argument_parser(self) -> argparse.ArgumentParser:
        parser = argparse.ArgumentParser(
            description="Growth Progress Calculator - Calculate daily growth progress based on weather",
            formatter_class=argparse.RawDescriptionHelpFormatter,
            epilog="""
Examples:
  # Step 1: Generate crop profile
  agrr crop --query "rice Koshihikari" > rice_profile.json
  
  # Step 2: Get weather data
  agrr weather --location 35.6762,139.6503 --days 90 --json > weather.json
  
  # Step 3: Calculate growth progress
  agrr progress --crop-file rice_profile.json --start-date 2024-05-01 --weather-file weather.json
  
  # With JSON output
  agrr progress --crop-file tomato_profile.json --start-date 2024-04-15 --weather-file weather.json --format json

Weather File Format (JSON):
  {
    "latitude": 35.6762,
    "longitude": 139.6503,
    "data": [
      {
        "time": "2024-05-01",
        "temperature_2m_max": 25.5,
        "temperature_2m_min": 15.2,
        "temperature_2m_mean": 20.3
      }
    ]
  }

Output (Table):
  Date       | Temp(°C) | Daily GDD | Cumul GDD | Progress(%) | Stage
  -----------|----------|-----------|-----------|-------------|-------------
  2024-05-01 | 20.3     | 10.3      | 10.3      | 0.43%       | germination
  2024-05-02 | 22.5     | 12.5      | 22.8      | 0.95%       | germination

Output (JSON):
  {
    "crop": "rice",
    "variety": "Koshihikari",
    "start_date": "2024-05-01",
    "daily_progress": [
      {
        "date": "2024-05-01",
        "temperature": 20.3,
        "daily_gdd": 10.3,
        "cumulative_gdd": 10.3,
        "progress_percentage": 0.43,
        "current_stage": "germination"
      }
    ],
    "completion_date": "2024-09-15",
    "total_days": 137
  }

Note: 
  - Weather file can be generated using 'agrr weather' command with --json flag.
  - Crop profile file must be generated using 'agrr crop' command.
  - The crop profile file contains all growth stage requirements for the specified crop.
  - See 'agrr crop --help' for complete JSON format specification.
            """
        )

        parser.add_argument(
            "--crop-file",
            "-c",
            required=True,
            help='Path to crop profile file (JSON, generated by "agrr crop")',
        )
        parser.add_argument(
            "--start-date",
            "-s",
            required=True,
            help='Growth start date in YYYY-MM-DD format (e.g., "2024-05-01")',
        )
        parser.add_argument(
            "--weather-file",
            "-w",
            required=True,
            help='Path to weather data file (JSON or CSV)',
        )
        parser.add_argument(
            "--format",
            "-f",
            choices=["table", "json"],
            default="table",
            help="Output format (default: table)",
        )

        return parser

    def handle_progress_command(self, args) -> None:
        """Handle the progress calculation command."""
        # Parse start date
        try:
            start_date = datetime.strptime(args.start_date, "%Y-%m-%d")
        except ValueError:
            message = 'Error: Invalid date format. Use YYYY-MM-DD (e.g., "2024-05-01")'
            self.logger.error(message)
            print(message)
            return

        # Update presenter format
        self.presenter.output_format = args.format

        # Get crop profile to extract crop_id and variety for RequestDTO
        # Gateway is already configured with the file path in cli.py
        try:
            crop_profile = self.crop_profile_gateway.get()
            crop_id = crop_profile.crop.crop_id
            variety = crop_profile.crop.variety
        except Exception as e:
            self.logger.error(f"Error loading crop profile: {str(e)}")
            return

        # Create request DTO
        request = GrowthProgressCalculateRequestDTO(
            crop_id=crop_id,
            variety=variety,
            start_date=start_date,
        )

        # Execute use case
        try:
            response = self.execute(request)
            self.presenter.present(response)
        except Exception as e:
            self.logger.error(f"Error calculating growth progress: {str(e)}")
            import traceback
            self.logger.error(traceback.format_exc())

    def run(self, args: Optional[list] = None) -> None:
        """Run the controller with CLI arguments."""
        parser = self.create_argument_parser()
        parsed_args = parser.parse_args(args)

        # No subcommands - directly handle the progress command
        self.handle_progress_command(parsed_args)

